---
- hosts: all
  become: true
  gather_facts: false

  vars:
    users:
      - username: devops_1
        groupname: devops_1
      - username: test_1
        groupname: test_1

  tasks:
    - name: Install required packages
      package:
        name: "{{ netology-ml }}"
      vars:
        packages:
          - net-tools
          - git
          - tree
          - htop
          - mc
          - vim

    - name: Update the system
      apt:
        upgrade: full
        autoremove: yes

    - name: Copy test file
      copy:
        src: test.txt
        dest: /home/devops_1/test.txt

    - name: Create users and directories
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groupname }}"
        shell: /bin/bash
        createhome: yes
        comment: User for testing
        append: yes
      with_items: "{{ users }}"

    - name: Create user directory
      file:
        path: "/home/{{ item.username }}"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.groupname }}"
        mode: '0755'
      with_items: "{{ users }}"

    - name: Ping host to check connectivity
      ping:
